# Generated by Django 4.1.2 on 2022-11-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='science',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
