# Generated by Django 4.1.2 on 2022-10-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_remove_test_name_test_answer_id_alter_test_admin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='answer_id',
        ),
        migrations.AddField(
            model_name='test',
            name='answer_id',
            field=models.ManyToManyField(blank=True, to='tests.answers'),
        ),
    ]
