# Generated by Django 4.1.2 on 2022-10-31 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('results', '0004_alter_result_user_id'),
        ('tests', '0004_remove_test_answer_id_test_answer_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
    ]
